-- =============================================================
-- Seed: ~40 canonical skills with aliases
-- Idempotent (re-runnable): upserts on skills(name).
-- Run after supabase/schema.sql.
-- =============================================================

INSERT INTO public.skills (name, aliases, category) VALUES
  ('JavaScript',  ARRAY['JS','Javascript','ECMAScript','ES6','ES2015+'], 'frontend'),
  ('TypeScript',  ARRAY['TS','Typescript','TSX'], 'frontend'),
  ('React',       ARRAY['ReactJS','React.js','Reactjs'], 'frontend'),
  ('Next.js',     ARRAY['NextJS','Next','Nextjs'], 'frontend'),
  ('Vue.js',      ARRAY['VueJS','Vue','Vuejs','Nuxt','Nuxt.js'], 'frontend'),
  ('Angular',     ARRAY['AngularJS','Angularjs','Angular 2+'], 'frontend'),
  ('HTML',        ARRAY['HTML5','html','Semantic HTML'], 'frontend'),
  ('CSS',         ARRAY['CSS3','css','Flexbox','Grid'], 'frontend'),
  ('Tailwind CSS',ARRAY['Tailwind','tailwindcss','TailwindCSS'], 'frontend'),
  ('Redux',       ARRAY['React Redux','Redux Toolkit','RTK'], 'frontend'),
  ('Node.js',     ARRAY['NodeJS','Node','nodejs','Nodejs'], 'backend'),
  ('Express.js',  ARRAY['Express','ExpressJS','Expressjs'], 'backend'),
  ('Python',      ARRAY['py','Python3','python3'], 'backend'),
  ('Django',      ARRAY['django','Django REST','DRF'], 'backend'),
  ('Flask',       ARRAY['flask'], 'backend'),
  ('FastAPI',     ARRAY['fast-api','fastapi','Fast Api'], 'backend'),
  ('Java',        ARRAY['java','Core Java','Java 8+'], 'backend'),
  ('Spring Boot', ARRAY['Spring','SpringBoot','Spring Framework'], 'backend'),
  ('Go',          ARRAY['Golang','GoLang','golang'], 'backend'),
  ('Rust',        ARRAY['rust'], 'backend'),
  ('GraphQL',     ARRAY['graphql','Graphql','Apollo','Hasura'], 'backend'),
  ('REST APIs',   ARRAY['REST','Rest API','RESTful','RESTful APIs','Restful'], 'backend'),
  ('PostgreSQL',  ARRAY['Postgres','postgres','pgsql','psql','Postgresql'], 'backend'),
  ('MySQL',       ARRAY['mysql','Mysql','MariaDB','mariadb'], 'backend'),
  ('MongoDB',     ARRAY['mongo','Mongo','mongodb','Mongoose','mongoose'], 'backend'),
  ('Redis',       ARRAY['redis','Upstash','upstash'], 'backend'),
  ('Supabase',    ARRAY['supabase'], 'backend'),
  ('Firebase',    ARRAY['firebase','Firestore','firestore'], 'backend'),
  ('Prisma',      ARRAY['prisma','Prisma ORM'], 'backend'),
  ('Docker',      ARRAY['docker','Docker Compose','docker-compose','Containerization'], 'devops_cloud'),
  ('Kubernetes',  ARRAY['K8s','k8s','K8S','Kube'], 'devops_cloud'),
  ('AWS',         ARRAY['Amazon Web Services','aws','EC2','S3','Lambda'], 'devops_cloud'),
  ('CI/CD',       ARRAY['CICD','Continuous Integration','Continuous Deployment','GitHub Actions','Github Actions','GitLab CI'], 'devops_cloud'),
  ('Git',         ARRAY['git','Version Control','Github','GitHub','GitLab','gitlab'], 'tools'),
  ('Linux',       ARRAY['linux','Unix','unix','Bash','bash','Shell'], 'tools'),
  ('Figma',       ARRAY['figma','FigJam','UI Design'], 'tools'),
  ('React Native',ARRAY['react-native','React-Native','react native','Expo','expo'], 'mobile'),
  ('Flutter',     ARRAY['flutter','Dart','dart'], 'mobile'),
  ('Swift',       ARRAY['swift','iOS','ios','SwiftUI','UIKit','Xcode'], 'mobile'),
  ('Kotlin',      ARRAY['kotlin','Android','android','Jetpack Compose'], 'mobile'),
  ('Pandas',      ARRAY['pandas','Data Analysis'], 'data_ai'),
  ('NumPy',       ARRAY['numpy','Numpy','Numerical Computing'], 'data_ai'),
  ('PyTorch',     ARRAY['pytorch','Pytorch','Torch'], 'data_ai'),
  ('TensorFlow',  ARRAY['tensorflow','Tensorflow','Keras','keras'], 'data_ai'),
  ('scikit-learn',ARRAY['sklearn','Sklearn','SciKit-Learn','Machine Learning'], 'data_ai'),
  ('OpenAI API',  ARRAY['OpenAI','openai','LLM','LLMs','LangChain','langchain','RAG','Prompt Engineering'], 'data_ai')
ON CONFLICT (name) DO UPDATE SET
  aliases  = EXCLUDED.aliases,
  category = EXCLUDED.category;
