/**
 * Canonical skill list + alias map for dropdown / normalization.
 * Mirrors docs/04: free entry → normalized to canonical
 * (JS→JavaScript, ReactJS→React, Postgres→PostgreSQL, ML→Machine Learning).
 */

export const CANONICAL_SKILLS = [
  // Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Go",
  "Rust",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "SQL",
  "Kotlin",
  "Swift",
  "Dart",
  "Scala",
  "Elixir",
  "Haskell",
  "C",
  "Objective-C",
  "Shell",
  "Bash",
  "Perl",
  "R",
  "MATLAB",
  // Frontend — frameworks / libraries
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "SvelteKit",
  "Remix",
  "Astro",
  "Nuxt.js",
  "Gatsby",
  "Redux",
  "Zustand",
  "Recoil",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "Styled Components",
  "Sass",
  "Less",
  "jQuery",
  "Electron",
  "Three.js",
  "D3.js",
  "Chart.js",
  "Vite",
  "Webpack",
  // Backend — frameworks / runtimes
  "Node.js",
  "Express",
  "NestJS",
  "Koa",
  "Fastify",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Spring",
  "Laravel",
  "Ruby on Rails",
  "Phoenix",
  ".NET",
  "ASP.NET",
  "Gin",
  "Echo",
  "Actix",
  // Data — databases / ORMs / warehouses
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "SQLite",
  "Cassandra",
  "DynamoDB",
  "MariaDB",
  "Oracle DB",
  "Firebase",
  "Supabase",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "Neo4j",
  "CouchDB",
  "Snowflake",
  "BigQuery",
  "Redshift",
  // Data / AI / ML
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Data Analysis",
  "Data Engineering",
  "MLOps",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "OpenAI",
  "LangChain",
  "Hugging Face",
  "Spark",
  "Hadoop",
  "Airflow",
  "Kafka",
  "RabbitMQ",
  "Tableau",
  "Power BI",
  "Looker",
  // Infra / DevOps / Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "GCP",
  "Azure",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Linux",
  "Jenkins",
  "Nginx",
  "Apache",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Vercel",
  "Netlify",
  "Heroku",
  "Cloudflare",
  "Helm",
  "Prometheus",
  "Grafana",
  "CircleCI",
  "GitHub Actions",
  // Mobile
  "React Native",
  "Flutter",
  "iOS",
  "Android",
  "SwiftUI",
  "Jetpack Compose",
  "Ionic",
  "Xamarin",
  "Cordova",
  "Capacitor",
  // Architecture / APIs / Practices
  "REST APIs",
  "GraphQL",
  "gRPC",
  "WebSockets",
  "WebRTC",
  "tRPC",
  "OpenAPI",
  "System Design",
  "Microservices",
  "OAuth",
  "Agile",
  "Scrum",
  // Testing / QA
  "Jest",
  "Vitest",
  "Cypress",
  "Playwright",
  "Testing Library",
  "Mocha",
  "JUnit",
  "Selenium",
  // Design / Tools / Software
  "UI Design",
  "UX Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Framer",
  "Webflow",
  "Photoshop",
  "Illustrator",
  "InDesign",
  "After Effects",
  "Canva",
  "Notion",
  "Jira",
  "Confluence",
  "Slack",
  "Asana",
  "Trello",
  "Linear",
  // Marketing / Growth / Business Software
  "SEO",
  "Content Marketing",
  "Digital Marketing",
  "Google Analytics",
  "Mixpanel",
  "Amplitude",
  "HubSpot",
  "Salesforce",
  "Excel",
  "Google Sheets",
  "PowerPoint",
  "Word",
  "Sales",
  "Copywriting",
] as const;

export type CanonicalSkill = (typeof CANONICAL_SKILLS)[number];

/** lowercase input → canonical. Covers docs/04 examples + common variants. */
export const SKILL_ALIASES: Record<string, CanonicalSkill> = {
  js: "JavaScript",
  javascript: "JavaScript",
  ts: "TypeScript",
  typescript: "TypeScript",
  reactjs: "React",
  react: "React",
  "react.js": "React",
  nextjs: "Next.js",
  "next.js": "Next.js",
  next: "Next.js",
  vue: "Vue.js",
  "vue.js": "Vue.js",
  vuetify: "Vue.js",
  nuxt: "Nuxt.js",
  "nuxt.js": "Nuxt.js",
  svelte: "Svelte",
  "sveltekit": "SvelteKit",
  remix: "Remix",
  astro: "Astro",
  gatsby: "Gatsby",
  angular: "Angular",
  "angular.js": "Angular",
  html: "HTML",
  css: "CSS",
  sass: "Sass",
  scss: "Sass",
  less: "Less",
  tailwind: "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  tailwindcss: "Tailwind CSS",
  bootstrap: "Bootstrap",
  mui: "Material UI",
  "material ui": "Material UI",
  "material-ui": "Material UI",
  chakra: "Chakra UI",
  "chakra ui": "Chakra UI",
  antd: "Ant Design",
  "ant design": "Ant Design",
  "styled components": "Styled Components",
  "styled-components": "Styled Components",
  jquery: "jQuery",
  electron: "Electron",
  threejs: "Three.js",
  "three.js": "Three.js",
  d3: "D3.js",
  "d3.js": "D3.js",
  nodejs: "Node.js",
  "node.js": "Node.js",
  node: "Node.js",
  expressjs: "Express",
  express: "Express",
  nestjs: "NestJS",
  "nest.js": "NestJS",
  koa: "Koa",
  fastify: "Fastify",
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  "spring boot": "Spring Boot",
  spring: "Spring",
  laravel: "Laravel",
  rails: "Ruby on Rails",
  "ruby on rails": "Ruby on Rails",
  phoenix: "Phoenix",
  dotnet: ".NET",
  ".net": ".NET",
  "asp.net": "ASP.NET",
  gin: "Gin",
  echo: "Echo",
  actix: "Actix",
  postgres: "PostgreSQL",
  postgresql: "PostgreSQL",
  psql: "PostgreSQL",
  mysql: "MySQL",
  mongo: "MongoDB",
  mongodb: "MongoDB",
  elastic: "Elasticsearch",
  elasticsearch: "Elasticsearch",
  redis: "Redis",
  sqlite: "SQLite",
  cassandra: "Cassandra",
  dynamodb: "DynamoDB",
  "dynamo db": "DynamoDB",
  mariadb: "MariaDB",
  oracle: "Oracle DB",
  firebase: "Firebase",
  supabase: "Supabase",
  prisma: "Prisma",
  typeorm: "TypeORM",
  sequelize: "Sequelize",
  mongoose: "Mongoose",
  neo4j: "Neo4j",
  snowflake: "Snowflake",
  bigquery: "BigQuery",
  redshift: "Redshift",
  ml: "Machine Learning",
  "machine learning": "Machine Learning",
  dl: "Deep Learning",
  "deep learning": "Deep Learning",
  nlp: "NLP",
  "computer vision": "Computer Vision",
  "data analysis": "Data Analysis",
  "data engineering": "Data Engineering",
  mlops: "MLOps",
  pandas: "Pandas",
  numpy: "NumPy",
  tensorflow: "TensorFlow",
  tf: "TensorFlow",
  pytorch: "PyTorch",
  keras: "Keras",
  "scikit-learn": "Scikit-learn",
  sklearn: "Scikit-learn",
  openai: "OpenAI",
  langchain: "LangChain",
  "hugging face": "Hugging Face",
  spark: "Spark",
  hadoop: "Hadoop",
  airflow: "Airflow",
  kafka: "Kafka",
  rabbitmq: "RabbitMQ",
  tableau: "Tableau",
  powerbi: "Power BI",
  "power bi": "Power BI",
  looker: "Looker",
  py: "Python",
  python: "Python",
  golang: "Go",
  go: "Go",
  rust: "Rust",
  kotlin: "Kotlin",
  swift: "Swift",
  dart: "Dart",
  scala: "Scala",
  elixir: "Elixir",
  haskell: "Haskell",
  k8s: "Kubernetes",
  kubernetes: "Kubernetes",
  dockers: "Docker",
  docker: "Docker",
  aws: "AWS",
  gcp: "GCP",
  azure: "Azure",
  terraform: "Terraform",
  ansible: "Ansible",
  linux: "Linux",
  jenkins: "Jenkins",
  nginx: "Nginx",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  vercel: "Vercel",
  netlify: "Netlify",
  heroku: "Heroku",
  cloudflare: "Cloudflare",
  helm: "Helm",
  prometheus: "Prometheus",
  grafana: "Grafana",
  "react native": "React Native",
  reactnative: "React Native",
  flutter: "Flutter",
  ios: "iOS",
  android: "Android",
  ionic: "Ionic",
  xamarin: "Xamarin",
  rest: "REST APIs",
  "rest api": "REST APIs",
  "rest apis": "REST APIs",
  restapi: "REST APIs",
  graphql: "GraphQL",
  grpc: "gRPC",
  websocket: "WebSockets",
  websockets: "WebSockets",
  webrtc: "WebRTC",
  trpc: "tRPC",
  systemdesign: "System Design",
  "system design": "System Design",
  microservices: "Microservices",
  oauth: "OAuth",
  agile: "Agile",
  scrum: "Scrum",
  jest: "Jest",
  vitest: "Vitest",
  cypress: "Cypress",
  playwright: "Playwright",
  figma: "Figma",
  "adobe xd": "Adobe XD",
  sketch: "Sketch",
  framer: "Framer",
  webflow: "Webflow",
  photoshop: "Photoshop",
  illustrator: "Illustrator",
  notion: "Notion",
  jira: "Jira",
  confluence: "Confluence",
  slack: "Slack",
  seo: "SEO",
  "google analytics": "Google Analytics",
  ga: "Google Analytics",
  mixpanel: "Mixpanel",
  amplitude: "Amplitude",
  hubspot: "HubSpot",
  salesforce: "Salesforce",
  excel: "Excel",
  sales: "Sales",
};

/** Normalize a free-text skill to canonical where possible. */
export function normalizeSkill(input: string): string {
  const key = input.trim().toLowerCase();
  if (!key) return input;
  return SKILL_ALIASES[key] ?? input.trim();
}

/** Dedupe (case-insensitive) + normalize a skill list. */
export function normalizeSkills(skills: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of skills) {
    const n = normalizeSkill(s);
    const k = n.toLowerCase();
    if (k && !seen.has(k)) {
      seen.add(k);
      out.push(n);
    }
  }
  return out;
}

export const DOMAINS = [
  "Software Development",
  "Data / AI",
  "Design",
  "Marketing",
  "Sales",
  "Product",
  "Operations",
  "Finance",
  "HR",
  "Other",
] as const;

export const SENIORITIES = [
  "intern",
  "junior",
  "mid",
  "senior",
  "lead",
] as const;

export const REMOTE_PREFS = ["onsite", "hybrid", "remote"] as const;

export const SALARY_FREQUENCIES = ["hourly", "monthly", "yearly"] as const;

export const EMPLOYMENT_TYPES = [
  "full-time",
  "part-time",
  "contract",
  "internship",
  "freelance",
] as const;

export const LOCATIONS = [
  "Remote",
  // India — Tier 1 metros
  "Bengaluru",
  "Mumbai",
  "Delhi",
  "New Delhi",
  "Hyderabad",
  "Chennai",
  "Pune",
  "Kolkata",
  "Ahmedabad",
  // India — NCR
  "Noida",
  "Greater Noida",
  "Gurgaon",
  "Gurugram",
  "Ghaziabad",
  "Faridabad",
  "Navi Mumbai",
  // India — Tier 2 / major
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Patna",
  "Vadodara",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Meerut",
  "Rajkot",
  "Varanasi",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Prayagraj",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubballi",
  "Mysuru",
  "Tiruchirappalli",
  "Trichy",
  "Bareilly",
  "Aligarh",
  "Moradabad",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Thiruvananthapuram",
  "Kochi",
  "Saharanpur",
  "Gorakhpur",
  "Bikaner",
  "Amravati",
  "Dehradun",
  "Shimla",
  "Udaipur",
  "Ujjain",
  "Jhansi",
  "Belgaum",
  "Mangaluru",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Maheshtala",
  "Tiruppur",
  "Davanagere",
  "Kozhikode",
  "Akola",
  "Kurnool",
  "Bokaro",
  "Bellary",
  "Patiala",
  "Agartala",
  "Bhagalpur",
  "Muzaffarnagar",
  "Latur",
  "Dhule",
  "Tirupati",
  "Rohtak",
  "Sangli",
  "Karimnagar",
  "Nellore",
  "Jammu",
  "Srinagar",
  "Jamnagar",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Kalaburagi",
  "Loni",
  "Siliguri",
  "Ulhasnagar",
  // Global — tech hubs
  "San Francisco",
  "New York",
  "Austin",
  "Seattle",
  "Boston",
  "Chicago",
  "Los Angeles",
  "Denver",
  "Toronto",
  "Vancouver",
  "London",
  "Berlin",
  "Amsterdam",
  "Paris",
  "Dublin",
  "Singapore",
  "Dubai",
  "Abu Dhabi",
  "Doha",
  "Riyadh",
  "Sydney",
  "Melbourne",
  "Tokyo",
  "Osaka",
  "Seoul",
  "Hong Kong",
  "Bangkok",
  "Kuala Lumpur",
  "Jakarta",
  "Manila",
  "Zurich",
  "Stockholm",
  "Oslo",
  "Copenhagen",
  "Helsinki",
  "Barcelona",
  "Madrid",
  "Milan",
  "Warsaw",
  "Krakow",
  "Lisbon",
  "Tel Aviv",
  "Cape Town",
  "Johannesburg",
  "Lagos",
  "Nairobi",
  "São Paulo",
  "Mexico City",
  "Buenos Aires",
] as const;
