export const CANONICAL_SKILLS = [
  ".NET",
  "ABAP",
  "Accessibility",
  "Account Management",
  "Accounting",
  "Active Directory",
  "Actix",
  "Ada",
  "Adobe XD",
  "Affiliate Marketing",
  "After Effects",
  "Agile",
  "Agile Coaching",
  "AI Agents",
  "Airflow",
  "Alpine.js",
  "Amazon Aurora",
  "Amazon SQS",
  "Amplitude",
  "Android",
  "Android Studio",
  "Angular",
  "AngularJS",
  "Anomaly Detection",
  "Ansible",
  "Ant Design",
  "Apache",
  "Apache Flink",
  "Apache NiFi",
  "API Testing",
  "Apollo Client",
  "Appium",
  "Application Security",
  "Arabic",
  "Arduino",
  "Argo CD",
  "ARKit",
  "Artificial Intelligence",
  "Asana",
  "ASP.NET",
  "ASP.NET Core",
  "Assembly",
  "Astro",
  "Augmented Reality",
  "AutoHotkey",
  "AWS",
  "AWS Lambda",
  "Azure",
  "Azure Data Factory",
  "Azure Pipelines",
  "B2B Sales",
  "Babel",
  "Babylon.js",
  "Balsamiq",
  "Bash",
  "BDD",
  "BeautifulSoup",
  "BigQuery",
  "Bitbucket",
  "Blazor",
  "Blender",
  "Blockchain",
  "Bootstrap",
  "Brand Strategy",
  "Bulma",
  "Bun",
  "Burp Suite",
  "Business Analysis",
  "Business Development",
  "C",
  "C#",
  "C++",
  "Canva",
  "Capacitor",
  "Cassandra",
  "CCNA",
  "Celery",
  "Chakra UI",
  "Chart.js",
  "ChatGPT",
  "Chroma",
  "CI/CD",
  "CircleCI",
  "Claude",
  "ClickHouse",
  "Clojure",
  "Cloud Security",
  "Cloudflare",
  "CloudFormation",
  "COBOL",
  "CockroachDB",
  "Code Review",
  "CoffeeScript",
  "Cold Calling",
  "Common Lisp",
  "Communication",
  "Computer Vision",
  "Confluence",
  "Consul",
  "Content Marketing",
  "Content Strategy",
  "Content Writing",
  "Conversion Rate Optimization",
  "Copywriting",
  "Cordova",
  "Core Data",
  "Cosmos DB",
  "CouchDB",
  "CRM",
  "Cryptocurrency",
  "Cryptography",
  "Crystal",
  "CSS",
  "Cucumber",
  "Cursor",
  "Customer Success",
  "Customer Support",
  "Cybersecurity",
  "Cypress",
  "D3.js",
  "Dagster",
  "Dart",
  "Data Analysis",
  "Data Engineering",
  "Data Mining",
  "Data Modeling",
  "Data Pipelines",
  "Data Warehouse",
  "Databricks",
  "Datadog",
  "dbt",
  "Deep Learning",
  "DeFi",
  "Delta Lake",
  "Design Systems",
  "Design Thinking",
  "Developer Advocacy",
  "Developer Relations",
  "Digital Marketing",
  "Django",
  "DNS",
  "Docker",
  "Docker Compose",
  "Documentation",
  "Drizzle ORM",
  "DuckDB",
  "DynamoDB",
  "Echo",
  "Elasticsearch",
  "Electron",
  "Elixir",
  "ELK Stack",
  "Elm",
  "Email Marketing",
  "Embedded C",
  "Embedded Systems",
  "English",
  "Entity Framework",
  "Erlang",
  "ERP",
  "esbuild",
  "ESP32",
  "Ethereum",
  "Ethical Hacking",
  "ETL",
  "Excel",
  "Expo",
  "Express",
  "F#",
  "Facebook Ads",
  "FastAPI",
  "Fastify",
  "Figma",
  "Financial Analysis",
  "Fine-Tuning",
  "Firebase",
  "Firestore",
  "Firewalls",
  "Flask",
  "Flutter",
  "Formik",
  "Fortran",
  "Framer",
  "French",
  "Game Design",
  "GameMaker",
  "Gatsby",
  "GCP",
  "GDPR",
  "GDScript",
  "Generative AI",
  "German",
  "ggplot2",
  "Gin",
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitHub Copilot",
  "GitLab",
  "GitLab CI",
  "GitOps",
  "GLSL",
  "Go",
  "Go-to-Market",
  "Godot",
  "Google Ads",
  "Google Analytics",
  "Google Colab",
  "Google Gemini",
  "Google Sheets",
  "Google Workspace",
  "Grafana",
  "Graphic Design",
  "GraphQL",
  "Groovy",
  "Growth Marketing",
  "gRPC",
  "GSAP",
  "Gulp",
  "Hadoop",
  "HAProxy",
  "Hardhat",
  "Haskell",
  "Headless UI",
  "Helm",
  "Heroku",
  "Hibernate",
  "Hindi",
  "Hive",
  "HTML",
  "htmx",
  "HubSpot",
  "Hugging Face",
  "Human Resources",
  "Illustrator",
  "Incident Response",
  "InDesign",
  "Influencer Marketing",
  "InfluxDB",
  "Informatica",
  "Information Architecture",
  "Interaction Design",
  "InVision",
  "Ionic",
  "iOS",
  "IoT",
  "IPFS",
  "Istio",
  "ITIL",
  "Japanese",
  "Java",
  "JavaScript",
  "JAX",
  "Jenkins",
  "Jest",
  "Jetpack Compose",
  "Jira",
  "JMeter",
  "jQuery",
  "Julia",
  "JUnit",
  "Jupyter",
  "Kafka",
  "Kanban",
  "Keras",
  "Keyword Research",
  "Koa",
  "Kotlin",
  "Kotlin Multiplatform",
  "Kubernetes",
  "LangChain",
  "LangGraph",
  "Laravel",
  "Large Language Models",
  "Lead Generation",
  "Lean",
  "Less",
  "Level Design",
  "Linear",
  "Linux",
  "Lit",
  "LlamaIndex",
  "Looker",
  "Looker Studio",
  "Lua",
  "Machine Learning",
  "Mandarin",
  "Manual Testing",
  "MariaDB",
  "Marketing Automation",
  "Marketing Strategy",
  "Material UI",
  "MATLAB",
  "Matplotlib",
  "Metabase",
  "Meteor",
  "Microcontrollers",
  "Micronaut",
  "Microservices",
  "Microsoft 365",
  "Microsoft Teams",
  "Milvus",
  "Miro",
  "Mixed Reality",
  "Mixpanel",
  "MLflow",
  "MLOps",
  "MobX",
  "Mocha",
  "MongoDB",
  "Mongoose",
  "Motion Design",
  "MQTT",
  "MySQL",
  "NATS",
  "Negotiation",
  "Neo4j",
  "NestJS",
  "Netlify",
  "Network Engineering",
  "Networking",
  "New Relic",
  "Next.js",
  "NFT",
  "Nginx",
  "Nim",
  "NLP",
  "Node.js",
  "Notion",
  "NumPy",
  "Nuxt.js",
  "Nx",
  "OAuth",
  "Objective-C",
  "Observability",
  "OCaml",
  "OKRs",
  "Ollama",
  "Open Source",
  "OpenAI",
  "OpenAPI",
  "OpenCV",
  "OpenGL",
  "OpenShift",
  "OpenTelemetry",
  "Oracle DB",
  "OWASP",
  "Pandas",
  "Parcel",
  "Payroll",
  "PCB Design",
  "Penetration Testing",
  "Performance Marketing",
  "Performance Testing",
  "Perl",
  "Perplexity",
  "pgvector",
  "Phaser",
  "Phoenix",
  "Photoshop",
  "PHP",
  "Pinecone",
  "Playwright",
  "PLC",
  "Plotly",
  "PostCSS",
  "PostgreSQL",
  "Postman",
  "Power BI",
  "PowerPoint",
  "PowerShell",
  "PPC",
  "Preact",
  "Prefect",
  "Presto",
  "PRINCE2",
  "Prioritization",
  "Prisma",
  "Problem Solving",
  "Product Management",
  "Product Roadmapping",
  "Product Strategy",
  "Program Management",
  "Project Management",
  "Prolog",
  "Prometheus",
  "Prompt Engineering",
  "Prototyping",
  "Public Speaking",
  "Pulumi",
  "Puppet",
  "Puppeteer",
  "Python",
  "PyTorch",
  "Qdrant",
  "Qlik",
  "Quarkus",
  "Qwik",
  "R",
  "RabbitMQ",
  "Radix UI",
  "RAG",
  "Rancher",
  "Raspberry Pi",
  "React",
  "React Hook Form",
  "React Native",
  "Recoil",
  "Recommendation Systems",
  "Recruiting",
  "Redis",
  "Redshift",
  "Redux",
  "Redux Toolkit",
  "Regression Testing",
  "Reinforcement Learning",
  "Remix",
  "REST APIs",
  "Risk Management",
  "Robotics",
  "Rollup",
  "Room",
  "ROS",
  "RTOS",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "RxJS",
  "SAFe",
  "Sales",
  "Salesforce",
  "SAP",
  "SAS",
  "Sass",
  "Scala",
  "Scheme",
  "Scikit-learn",
  "Scrapy",
  "Scrum",
  "Scrum Master",
  "Seaborn",
  "Selenium",
  "Semantic Search",
  "Sentry",
  "SEO",
  "Sequelize",
  "Server-Sent Events",
  "Serverless",
  "shadcn/ui",
  "Shader Programming",
  "Shell",
  "Shiny",
  "Sidekiq",
  "SIEM",
  "Site Reliability Engineering",
  "Six Sigma",
  "Sketch",
  "Slack",
  "Smart Contracts",
  "Snowflake",
  "SOAP",
  "Social Media Marketing",
  "Socket.IO",
  "Solana",
  "Solidity",
  "SolidJS",
  "Solution Selling",
  "SonarQube",
  "Spanish",
  "Spark",
  "Speech Recognition",
  "Spinnaker",
  "Spring",
  "Spring Boot",
  "SPSS",
  "SQL",
  "SQLAlchemy",
  "SQLite",
  "Stable Diffusion",
  "Stakeholder Management",
  "Statistics",
  "Storybook",
  "Strapi",
  "Streamlit",
  "Styled Components",
  "Supabase",
  "Supply Chain Management",
  "Svelte",
  "SvelteKit",
  "SWC",
  "Swift",
  "SwiftUI",
  "System Administration",
  "System Design",
  "Tableau",
  "Tabnine",
  "Tailwind CSS",
  "Talent Acquisition",
  "TanStack Query",
  "TCP/IP",
  "TDD",
  "Team Management",
  "TeamCity",
  "Technical SEO",
  "Technical Support",
  "Technical Writing",
  "TensorFlow",
  "Terraform",
  "Test Automation",
  "Testing Library",
  "Threat Modeling",
  "Three.js",
  "TimescaleDB",
  "Transformers",
  "Travis CI",
  "Trello",
  "Trino",
  "tRPC",
  "Turbopack",
  "Turborepo",
  "TypeORM",
  "TypeScript",
  "Typography",
  "Ubuntu",
  "UI Design",
  "Unit Testing",
  "Unity",
  "Unreal Engine",
  "Usability Testing",
  "User Stories",
  "UX Design",
  "UX Research",
  "Vagrant",
  "Vault",
  "VB.NET",
  "VBA",
  "Vector Databases",
  "Vercel",
  "Verilog",
  "VHDL",
  "Virtual Reality",
  "Visual Design",
  "Vite",
  "Vitest",
  "vLLM",
  "VMware",
  "VPN",
  "Vue.js",
  "Vulkan",
  "Waterfall",
  "Weaviate",
  "Web Components",
  "Web Scraping",
  "Web3",
  "Webflow",
  "WebGL",
  "WebGPU",
  "Webpack",
  "WebRTC",
  "WebSockets",
  "WebXR",
  "Weights & Biases",
  "Windows Server",
  "Windsurf",
  "Wireframing",
  "Wireshark",
  "Word",
  "Xamarin",
  "Xcode",
  "XGBoost",
  "XState",
  "YOLO",
  "Zapier",
  "Zendesk",
  "Zero Trust",
  "Zig",
  "Zod",
  "Zoom",
  "Zustand",
] as const;

export type CanonicalSkill = (typeof CANONICAL_SKILLS)[number];

export const SKILL_ALIASES: Record<string, CanonicalSkill> = {
  js: "JavaScript",
  javascript: "JavaScript",
  ts: "TypeScript",
  typescript: "TypeScript",
  reactjs: "React",
  react: "React",
  "react.js": "React",
  nextjs: "Next.js",
  "next.js": "Next.js",
  next: "Next.js",
  vue: "Vue.js",
  "vue.js": "Vue.js",
  vuetify: "Vue.js",
  nuxt: "Nuxt.js",
  "nuxt.js": "Nuxt.js",
  svelte: "Svelte",
  "sveltekit": "SvelteKit",
  remix: "Remix",
  astro: "Astro",
  gatsby: "Gatsby",
  angular: "Angular",
  "angular.js": "Angular",
  html: "HTML",
  css: "CSS",
  sass: "Sass",
  scss: "Sass",
  less: "Less",
  tailwind: "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  tailwindcss: "Tailwind CSS",
  bootstrap: "Bootstrap",
  mui: "Material UI",
  "material ui": "Material UI",
  "material-ui": "Material UI",
  chakra: "Chakra UI",
  "chakra ui": "Chakra UI",
  antd: "Ant Design",
  "ant design": "Ant Design",
  "styled components": "Styled Components",
  "styled-components": "Styled Components",
  jquery: "jQuery",
  electron: "Electron",
  threejs: "Three.js",
  "three.js": "Three.js",
  d3: "D3.js",
  "d3.js": "D3.js",
  nodejs: "Node.js",
  "node.js": "Node.js",
  node: "Node.js",
  expressjs: "Express",
  express: "Express",
  nestjs: "NestJS",
  "nest.js": "NestJS",
  koa: "Koa",
  fastify: "Fastify",
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  "spring boot": "Spring Boot",
  spring: "Spring",
  laravel: "Laravel",
  rails: "Ruby on Rails",
  "ruby on rails": "Ruby on Rails",
  phoenix: "Phoenix",
  dotnet: ".NET",
  ".net": ".NET",
  "asp.net": "ASP.NET",
  gin: "Gin",
  echo: "Echo",
  actix: "Actix",
  postgres: "PostgreSQL",
  postgresql: "PostgreSQL",
  psql: "PostgreSQL",
  mysql: "MySQL",
  mongo: "MongoDB",
  mongodb: "MongoDB",
  elastic: "Elasticsearch",
  elasticsearch: "Elasticsearch",
  redis: "Redis",
  sqlite: "SQLite",
  cassandra: "Cassandra",
  dynamodb: "DynamoDB",
  "dynamo db": "DynamoDB",
  mariadb: "MariaDB",
  oracle: "Oracle DB",
  firebase: "Firebase",
  supabase: "Supabase",
  prisma: "Prisma",
  typeorm: "TypeORM",
  sequelize: "Sequelize",
  mongoose: "Mongoose",
  neo4j: "Neo4j",
  snowflake: "Snowflake",
  bigquery: "BigQuery",
  redshift: "Redshift",
  ml: "Machine Learning",
  "machine learning": "Machine Learning",
  dl: "Deep Learning",
  "deep learning": "Deep Learning",
  nlp: "NLP",
  "computer vision": "Computer Vision",
  "data analysis": "Data Analysis",
  "data engineering": "Data Engineering",
  mlops: "MLOps",
  pandas: "Pandas",
  numpy: "NumPy",
  tensorflow: "TensorFlow",
  tf: "TensorFlow",
  pytorch: "PyTorch",
  keras: "Keras",
  "scikit-learn": "Scikit-learn",
  sklearn: "Scikit-learn",
  openai: "OpenAI",
  langchain: "LangChain",
  "hugging face": "Hugging Face",
  spark: "Spark",
  hadoop: "Hadoop",
  airflow: "Airflow",
  kafka: "Kafka",
  rabbitmq: "RabbitMQ",
  tableau: "Tableau",
  powerbi: "Power BI",
  "power bi": "Power BI",
  looker: "Looker",
  py: "Python",
  python: "Python",
  golang: "Go",
  go: "Go",
  rust: "Rust",
  kotlin: "Kotlin",
  swift: "Swift",
  dart: "Dart",
  scala: "Scala",
  elixir: "Elixir",
  haskell: "Haskell",
  k8s: "Kubernetes",
  kubernetes: "Kubernetes",
  dockers: "Docker",
  docker: "Docker",
  aws: "AWS",
  gcp: "GCP",
  azure: "Azure",
  terraform: "Terraform",
  ansible: "Ansible",
  linux: "Linux",
  jenkins: "Jenkins",
  nginx: "Nginx",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  vercel: "Vercel",
  netlify: "Netlify",
  heroku: "Heroku",
  cloudflare: "Cloudflare",
  helm: "Helm",
  prometheus: "Prometheus",
  grafana: "Grafana",
  "react native": "React Native",
  reactnative: "React Native",
  flutter: "Flutter",
  ios: "iOS",
  android: "Android",
  ionic: "Ionic",
  xamarin: "Xamarin",
  rest: "REST APIs",
  "rest api": "REST APIs",
  "rest apis": "REST APIs",
  restapi: "REST APIs",
  graphql: "GraphQL",
  grpc: "gRPC",
  websocket: "WebSockets",
  websockets: "WebSockets",
  webrtc: "WebRTC",
  trpc: "tRPC",
  systemdesign: "System Design",
  "system design": "System Design",
  microservices: "Microservices",
  oauth: "OAuth",
  agile: "Agile",
  scrum: "Scrum",
  jest: "Jest",
  vitest: "Vitest",
  cypress: "Cypress",
  playwright: "Playwright",
  figma: "Figma",
  "adobe xd": "Adobe XD",
  sketch: "Sketch",
  framer: "Framer",
  webflow: "Webflow",
  photoshop: "Photoshop",
  illustrator: "Illustrator",
  notion: "Notion",
  jira: "Jira",
  confluence: "Confluence",
  slack: "Slack",
  seo: "SEO",
  "google analytics": "Google Analytics",
  ga: "Google Analytics",
  mixpanel: "Mixpanel",
  amplitude: "Amplitude",
  hubspot: "HubSpot",
  salesforce: "Salesforce",
  excel: "Excel",
  sales: "Sales",
};

export function normalizeSkill(input: string): string {
  const key = input.trim().toLowerCase();
  if (!key) return input;
  return SKILL_ALIASES[key] ?? input.trim();
}

export function normalizeSkills(skills: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of skills) {
    const n = normalizeSkill(s);
    const k = n.toLowerCase();
    if (k && !seen.has(k)) {
      seen.add(k);
      out.push(n);
    }
  }
  return out;
}

export const DOMAINS = [
  "Software Development",
  "Data / AI",
  "Design",
  "Marketing",
  "Sales",
  "Product",
  "Operations",
  "Finance",
  "HR",
  "Other",
] as const;

export const SALARY_FREQUENCIES = ["hourly", "monthly", "yearly"] as const;

export const EMPLOYMENT_TYPES = [
  "full-time",
  "part-time",
  "contract",
  "internship",
  "freelance",
] as const;

export const LOCATIONS = [
  "Abidjan",
  "Abu Dhabi",
  "Accra",
  "Addis Ababa",
  "Adelaide",
  "Agartala",
  "Agra",
  "Ahmedabad",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alexandria",
  "Aligarh",
  "Almaty",
  "Alwar",
  "Amaravati",
  "Ambala",
  "Amman",
  "Amravati",
  "Amritsar",
  "Amsterdam",
  "Anantapur",
  "Asansol",
  "Astana",
  "Asunción",
  "Athens",
  "Atlanta",
  "Auckland",
  "Aurangabad",
  "Austin",
  "Baghdad",
  "Baku",
  "Bali",
  "Baltimore",
  "Bangalore",
  "Bangkok",
  "Barcelona",
  "Bareilly",
  "Basel",
  "Bathinda",
  "Beijing",
  "Beirut",
  "Belagavi",
  "Belgaum",
  "Belgrade",
  "Bellary",
  "Bengaluru",
  "Berhampur",
  "Berlin",
  "Bhagalpur",
  "Bhavnagar",
  "Bhilai",
  "Bhilwara",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Bilaspur",
  "Birmingham",
  "Bogotá",
  "Bokaro",
  "Boston",
  "Boulder",
  "Brasília",
  "Brisbane",
  "Bristol",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Busan",
  "Cairo",
  "Calgary",
  "Cali",
  "Cambridge",
  "Cape Town",
  "Caracas",
  "Casablanca",
  "Chandigarh",
  "Charlotte",
  "Chengdu",
  "Chennai",
  "Chiang Mai",
  "Chicago",
  "Christchurch",
  "Coimbatore",
  "Colombo",
  "Columbus",
  "Copenhagen",
  "Cuttack",
  "Da Nang",
  "Dakar",
  "Dallas",
  "Dammam",
  "Dar es Salaam",
  "Darbhanga",
  "Davanagere",
  "Dehradun",
  "Delhi",
  "Denver",
  "Detroit",
  "Dhaka",
  "Dhanbad",
  "Dharamshala",
  "Dhule",
  "Dibrugarh",
  "Dispur",
  "Doha",
  "Dubai",
  "Dublin",
  "Durgapur",
  "Edinburgh",
  "Edmonton",
  "Eindhoven",
  "Erbil",
  "Erode",
  "Faridabad",
  "Firozabad",
  "Frankfurt",
  "Fukuoka",
  "Gandhinagar",
  "Gangtok",
  "Gaya",
  "Geneva",
  "Ghaziabad",
  "Glasgow",
  "Gorakhpur",
  "Greater Noida",
  "Guadalajara",
  "Guangzhou",
  "Guntur",
  "Gurgaon",
  "Gurugram",
  "Guwahati",
  "Gwalior",
  "Haifa",
  "Haldwani",
  "Halifax",
  "Hamburg",
  "Hangzhou",
  "Hanoi",
  "Harare",
  "Haridwar",
  "Helsinki",
  "Hisar",
  "Ho Chi Minh City",
  "Hong Kong",
  "Houston",
  "Howrah",
  "Hubballi",
  "Hyderabad",
  "Imphal",
  "Indore",
  "Islamabad",
  "Istanbul",
  "Itanagar",
  "Jabalpur",
  "Jaipur",
  "Jakarta",
  "Jalandhar",
  "Jalgaon",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jeddah",
  "Jerusalem",
  "Jhansi",
  "Jodhpur",
  "Johannesburg",
  "Junagadh",
  "Kadapa",
  "Kakinada",
  "Kalaburagi",
  "Kalyan",
  "Kampala",
  "Kannur",
  "Kanpur",
  "Kansas City",
  "Kaohsiung",
  "Karachi",
  "Karimnagar",
  "Kathmandu",
  "Kharagpur",
  "Kigali",
  "Kinshasa",
  "Kochi",
  "Kohima",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Kota",
  "Kozhikode",
  "Krakow",
  "Kuala Lumpur",
  "Kurnool",
  "Kuwait City",
  "Kyiv",
  "Lagos",
  "Lahore",
  "Las Vegas",
  "Latur",
  "Leh",
  "Lima",
  "Lisbon",
  "London",
  "Loni",
  "Los Angeles",
  "Luanda",
  "Lucknow",
  "Ludhiana",
  "Luxembourg",
  "Lyon",
  "Madrid",
  "Madurai",
  "Maheshtala",
  "Malegaon",
  "Manama",
  "Manchester",
  "Mangaluru",
  "Manila",
  "Maputo",
  "Margao",
  "Marseille",
  "Medellín",
  "Meerut",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Minneapolis",
  "Mohali",
  "Monterrey",
  "Montevideo",
  "Montreal",
  "Moradabad",
  "Moscow",
  "Mountain View",
  "Mumbai",
  "Munich",
  "Muscat",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysuru",
  "Nagoya",
  "Nagpur",
  "Nairobi",
  "Nanded",
  "Nashik",
  "Nashville",
  "Navi Mumbai",
  "Nellore",
  "New Delhi",
  "New Orleans",
  "New York",
  "Noida",
  "Oakland",
  "Orlando",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Oxford",
  "Palo Alto",
  "Panaji",
  "Panama City",
  "Panchkula",
  "Panipat",
  "Panvel",
  "Paris",
  "Patiala",
  "Patna",
  "Perth",
  "Philadelphia",
  "Phnom Penh",
  "Phoenix",
  "Pittsburgh",
  "Portland",
  "Porto",
  "Prague",
  "Prayagraj",
  "Puducherry",
  "Pune",
  "Quito",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Raleigh",
  "Ranchi",
  "Remote",
  "Reykjavik",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Rohtak",
  "Rome",
  "Rotterdam",
  "Rourkela",
  "Sacramento",
  "Saharanpur",
  "Salem",
  "Salt Lake City",
  "Sambalpur",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Sangli",
  "Santiago",
  "São Paulo",
  "Seattle",
  "Secunderabad",
  "Seoul",
  "Shanghai",
  "Sharjah",
  "Shenzhen",
  "Shillong",
  "Shimla",
  "Shivamogga",
  "Silchar",
  "Siliguri",
  "Singapore",
  "Sofia",
  "Solapur",
  "Sonipat",
  "Srinagar",
  "St. Louis",
  "Stockholm",
  "Surat",
  "Sydney",
  "Taipei",
  "Tallinn",
  "Tampa",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "Thane",
  "Thanjavur",
  "The Hague",
  "Thiruvananthapuram",
  "Thoothukudi",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tiruppur",
  "Tokyo",
  "Toronto",
  "Trichy",
  "Tumakuru",
  "Udaipur",
  "Ujjain",
  "Ulhasnagar",
  "Vadodara",
  "Vancouver",
  "Varanasi",
  "Vellore",
  "Vienna",
  "Vientiane",
  "Vijayawada",
  "Vilnius",
  "Visakhapatnam",
  "Warangal",
  "Warsaw",
  "Washington DC",
  "Waterloo",
  "Wellington",
  "Winnipeg",
  "Yangon",
  "Yerevan",
  "Zagreb",
  "Zurich",
] as const;
